version: '3'

services:
  node_app:
    container_name: front-devops
    build:
      context: .
      dockerfile: dockerfile
    image: 197.26.204.208:8083/4twin1-g2-projetfinal-front:1.0
    ports:
      - "4200:4200"
    volumes:
      - .:/app
